image: python:3.7-stretch
stages:
  - test
  - deploy

before_script:
  - pip install --upgrade pip
  - pip install setuptools wheel

# test:
#   stage: test
#   script:
#     - pip install pytest
#     - pip install .

sdist:
  stage: deploy
  script:
    - python setup.py sdist
  artifacts:
    paths:
      - dist/*.tar.gz

wheel:
  stage: deploy
  script:
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
